version: '3.8'

services:
  nginx-service:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/default.conf:ro
      - ./RapidNoteFinderApi:/var/www/RapidNoteFinderApi
    depends_on:
      - database
      - app

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    extra_hosts:    # if we do not use windows then in order xdebug to work we need uncomment this parameter 
      - host.docker.internal:host-gateway
    volumes:
      - ./RapidNoteFinderApi:/var/www/RapidNoteFinderApi
    depends_on:
      - database

  database:
    image: mysql:8.1
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  node-service:
    build:
      context: .
      dockerfile: ./Dockernode
    ports:
      - "3000:3000"
    volumes:
      - ./RapidNoteFinderExt:/var/www/RapidNoteFinderExt
    working_dir: "/var/www/RapidNoteFinderExt"
    # restart: always
    tty: true
    
